/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wobiancao_ndkjnidemo_ndk_JniUtils */

#ifndef _Included_com_common_encodendk_JniUtils
#define _Included_com_common_encodendk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_encodendk_JniUtils
 * Method:    getKeyValue
 */
JNIEXPORT jbyteArray JNICALL Java_com_common_encodendk_JniUtils_getKeyValue(
		JNIEnv *, jclass);
/*
 * Class:     com_common_encodendk_JniUtils
 * Method:    getIv
 */
JNIEXPORT jbyteArray JNICALL Java_com_common_encodendk_JniUtils_getIv(JNIEnv *,
		jclass);

#ifdef __cplusplus
}
#endif
#endif
